### ISSUE TITLE
Support buffer slot capacity less than 64K

### ISSUE THREAD

**Issue by jfallows** [reaktivity/nukleus-tls.java#41]
Configure maximum packet size accordingly.

See [Java 9 `SSLParameters.setMaximumPacketSize(...)`](https://docs.oracle.com/javase/9/docs/api/javax/net/ssl/SSLParameters.html#setMaximumPacketSize-int-)

**Comment by dpwspoon** [comment]
Buffer slot capacity is currently limited to powers of two.  Any setting larger than the maximum packet size (16k + MAC + padding + 5), works.  32K is thus the smallest size possible today.

**Initial Discovery of Maximum Packet Size**

[SSLParameters.setMaximumPacketSize(...)](https://docs.oracle.com/javase/9/docs/api/javax/net/ssl/SSLParameters.html#setMaximumPacketSize-int-) Sets the maximum expected network packet size in bytes for SSL/TLS/DTLS records.  This will enforce that TLS does not read packets over that size.  It will throw an SSLException if a packet is given over that size.

Setting setMaximumPacketSize is done prior to handshaking.

Maximum Fragment Length Negotiation (MFLN) will allow negotiating that the client should not send packets of specified sizes.  Set via `jsse.enableMFLNExtension=true` with a set of values per [RFC](https://tools.ietf.org/html/rfc6066#section-4).

TLS requires client advertise extensions.  Wiresharking chrome on one sample page showed that the client (chrome) did not share that extension.  

The default Java API provides no way to see if the client negotiated the extension.  If the negotiation fails AND the client sends more payload then the connectivity will break.  

**References**
[Maximum Fragment Length Negotiation](https://docs.oracle.com/javase/9/security/java-secure-socket-extension-jsse-reference-guide.htm#JSSEC-GUID-41D5F11E-81BD-4C03-A315-48016D9B9B36)
[SSL Implementation Java 9](http://hg.openjdk.java.net/jdk9/jdk9/jdk/file/65464a307408/src/java.base/share/classes/sun/security/ssl)

**Potential Implementations/Work arounds**

We can observe the client handshake prior to providing it to SSLEngine.  If MFLN is negotiated we can set the maximum packet size.  Otherwise, we need to support buffering of slot capacity up to the max packet size.

There may be ways to limit the number of slots used in this worst case through group budgeting that limits use of shared resources

**Comment by robinzimmermann** [comment]
Moving to backlog in the performance release for now. To be determined if this is done in the performance release or moved to a future release.

**Comment by jfallows** [comment]
We'll revisit this again when Maximum Fragment Length Negotiation is more widely supported by browser clients.
